### PR TITLE
Fix compilation on MacOSX 

### PR DESCRIPTION
**Pull request by Lupino**

### CODE REVIEW

**Comment by lyokha** [comment]
Thanks! Merged.

1. Though uninitialized variables should work correctly even without initialization. Did you use some static code analyzer?
2. Now I see that there is no `pipe2()` in MacOSX, so I'll add non-blocking mode via `fcntl()`.

Cheers!

**Comment by lyokha** [comment]
I added `fcntl()`'s with `O_NONBLOCK` flag for pipe fds. Please check if it compiles at yours.

**Comment by Lupino** [comment]
`fcntl()` 's with `O_NONBLOCK` flag work for me on `MACOS`   

```diff
diff --git a/ngx_http_haskell_module.c b/ngx_http_haskell_module.c
index d3004d3..b185120 100644
--- a/ngx_http_haskell_module.c
+++ b/ngx_http_haskell_module.c
@@ -20,6 +20,7 @@
 #include <dlfcn.h>
 #include <HsFFI.h>
 #include <ghcversion.h>
+#include <fcntl.h>

 #ifdef NGX_HTTP_HASKELL_SHM_USE_SHARED_RLOCK
 #define NGX_HTTP_HASKELL_SHM_WLOCK  ngx_lock_fd(mcf->shm_lock_fd);
@@ -4559,7 +4560,7 @@ ngx_http_haskell_open_async_event_channel(ngx_fd_t fd[2])
 #endif
     return fd[0] == NGX_INVALID_FILE ? NGX_ERROR : NGX_OK;
 #else
-    return pipe(fd) == -1 ? NGX_ERROR : NGX_OK;
+    return fcntl(fd[0], O_NONBLOCK) == -1 ? NGX_ERROR : NGX_OK;
 #endif
 }
```

**Comment by lyokha** [comment]
Good. But `fcntl()` must aply to both `fd[0]` and `fd[1]` *after* `pipe()` (not *instead*!). Including of `fcntl.h` is not needed because `ngx_config.h` already includes all system-specific headers. Here is my diff:

```diff
--- a/ngx_http_haskell_module.c
+++ b/ngx_http_haskell_module.c
@@ -4559,7 +4559,16 @@ ngx_http_haskell_open_async_event_channel(ngx_fd_t fd[2])
 #endif
     return fd[0] == NGX_INVALID_FILE ? NGX_ERROR : NGX_OK;
 #else
-    return pipe(fd) == -1 ? NGX_ERROR : NGX_OK;
+    if (pipe(fd) == -1) {
+        return NGX_ERROR;
+    }
+    if (fcntl(fd[0], F_SETFL, O_NONBLOCK) == -1
+        || fcntl(fd[1], F_SETFL, O_NONBLOCK) == -1)
+    {
+        ngx_http_haskell_close_async_event_channel(NULL, fd);
+        return NGX_ERROR;
+    }
+    return NGX_OK;
 #endif
 }
 
@@ -4570,7 +4579,7 @@ ngx_http_haskell_close_async_event_channel(ngx_log_t *log, ngx_fd_t fd[2])
     ngx_int_t  i;
 
     for (i = 0; i < (fd[0] == fd[1] ? 1 : 2); i++) {
-        if (close(fd[i]) == -1) {
+        if (close(fd[i]) == -1 && log != NULL) {
             ngx_log_error(NGX_LOG_CRIT, log, ngx_errno,
                           "failed to close file descriptor of "
                           "async event channel");
```

You can simply pull this from this repository because it's already in.

**Comment by Lupino** [comment]
Thinks

**Pull request merged**
